run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - typecheck
    - errcheck
    - govet
    - staticcheck
  disable:
    - wsl
    - gochecknoinits

linters-settings:
  typecheck:
    compiler: gc
    build-tags: []
    skip-files:
      - "internal/fiber/domain/entities/*.go"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - colored-line-number
