version: '3.9'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    platform: linux/amd64
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./media:/root/media
    networks:
      - backend

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    restart: always
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
