name: CI/CD with Rollback

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Permite ejecución manual

jobs:
  test: # Permite los test que esten disponibles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6" # Usa tu versión de Go
      - name: Run Tests
        run: |
          go test -v ./...
          go mod tidy

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy to Staging
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} "
            cd /home/ubuntu/Inventori_ecommerce && \
            git pull origin main && \
            docker-compose -f docker-compose.dev.yml down && \
            docker-compose -f docker-compose.dev.yml up -d --build
          "

  approve-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.APPROVAL_TOKEN }}
          approvers: "Juan-Barraza"
          prompt: "✅ Staging deployment complete. Approve production deployment?"

  deploy-production:
    needs: approve-production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SSH_KEY }}
          known_hosts: ${{ secrets.PROD_KNOWN_HOSTS }}
      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} "
            cd /home/ubuntu/Inventori_ecommerce && \
            git pull origin main && \
            docker-compose -f docker-compose.prod.yml down && \
            docker-compose -f docker-compose.prod.yml up -d --build
          "
